// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storages

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Пользователи
type User struct {
	// ID пользователя
	UserID int32
	// Никнейм
	Username string
	// Имя
	FirstName string
	// Фамилия
	LastName string
	// Email
	Email string
	// Хэш пароля
	Passwhash string
	// Флаг активности уч. ползьзователя
	IsActive bool
	// Дата создания
	CreatedAt pgtype.Timestamptz
	// Дата удаления
	DeletedAt pgtype.Timestamptz
}

// Сессии пользователей
type UsersSession struct {
	// Ид сессии
	UsersSessionsID int32
	// Ид пользователя
	UserID int32
	// Токен сессии
	Token string
	// Дата и время создания сессии
	CreatedAt pgtype.Timestamptz
	// Флаг что сессия активна
	IsActive bool
	// Дата и время использование токена сессии
	UsedAt pgtype.Timestamptz
}
